# Dies ist das erste Play
- name: "Installiere einen Server"
  hosts: tsm
  gather_facts: true
  vars_files: 
    - "../vars/central_vars.yaml"
    - "../../credentials"
  
  tasks:
    - name: "# --- 01 - Register tsm-server with RHSM"
      redhat_subscription:
        state: present
        username: "{{ redhat_user }}"
        password: "{{ redhat_pass }}"
        #environment: Library
        autosubscribe: yes

    - name: "# --- 02 - Install prerequisites and software necessary programs"
      yum: 
        name: "{{ item }}"
        state: "present"
      with_items:
        - "nfs-utils.x86_64"


    - name: "# --- 03 - Erstelle Arbeitsverzeichnisse"
      file: 
        path: "{{ item }}"
        #mode: ""
        #owner: ""
        #group: ""
        state: directory
        recurse: true
      with_items:
        - "{{ mount_path_tsm }}"
        - "{{ mount_path_cdrom }}"
        - "{{ dir_work }}{{ dir_tsm }}{{ dir_tsm_extracted_install }}"

# Mounte NFS-Server-Verzeichnis zum Kopieren der Kickstart-Datei
    - name: "# --- 04 - Mounting NFS-Share"
      mount:
        fstype: nfs
        opts: "nfsvers=3,nolock"
        dump: "0"
        passno: "0"
        state: mounted
        src: "{{ nfs_server_name }}:{{ nfs_path }}"
        path: "{{ mount_path_tsm }}"

# Copy BIN-File
    - name: "# --- 05 - Copy BIN-File from NAS to {{ dir_work }}{{ dir_tsm }}{{ dir_tsm_extracted_install }}"
      copy:
        src: "{{ mount_path_tsm }}{{ nfs_path_bin_file }}"
        dest: "{{ dir_work }}{{ dir_tsm }}{{ dir_tsm_extracted_install }}{{ bin_file_name }}"
        remote_src: yes

# Extract the BIN-File
    - name: "# --- 06 - Extract BIN-File"
      shell: "{{ dir_work }}{{ dir_tsm }}{{ dir_tsm_extracted_install }}{{ bin_file_name }}"

# Erstelle den TSM-User
    - name: "# --- 07 - Erstelle den TSM-User {{ tsm_username }}"
      user:
        name: "{{ tsm_username }}"
        comment: "Dies ist der TSM-Installationsbenutzer"
        uid: 2222
        group: 1111
    

  
