# Dies ist das erste Play
- name: Installiere einen Server
  # Hier kann man die Hostnamen oder Groupnamen aus dem Inventory-File ansprechen, auf die das Playbook angewendet werden soll
  hosts: localhost
  # Sollen Daten über den remote-Host gesammelt werden und die facts-Variablen mit Werten gefüllt werden
  gather_facts: true
  # Hier beginnt die Variablen Deklaration
  vars:
    # Variable "user1" mit dem Wert "Patrick"
    user1: Patrick
    # Variable "passwd" mit dem Wert "Test"
    passwd: Test
  # Hier beginnen Tasks für das erste Play
  tasks:
    # Dies ist der erste Task
    - name: Installiere einen WebServer
      # Dies ist das Module YUM. 
      yum:
        # Dies ist der Package-Name inkl. Version
        # State=present bedeutet. Muss vorhanden sein, wenn nicht, wird es installiert.
        name: httpd
        # Als Status können die folgenden Werte verwendet werden
        # 'present' or 'installed', 'latest', or 'absent' or 'removed'
        state: present
    # Führe das Debug-Modul aus für den ersten Task aus
    - debug:
        # Hier wird eine Message ausgegeben und auf die Variable "user1" zugegriffen.
        msg: Dieses Playbook wurde von {{ user1 }} geschrieben.

    # Dies ist der zweite Task
    - name: Installiere Python
      # Dies ist das Module YUM. 
      yum:
        # Dies ist der Package-Name inkl. Version
        # Es wird die Software "zziplib" installiert
        name: zziplib.i686
        # Als Status können die folgenden Werte verwendet werden
        # 'present' or 'installed', 'latest', or 'absent' or 'removed'
        state: absent
    # Führe das Debug-Modul aus für den zweiten Task aus
    - debug:
        # Hier wird eine Message ausgegeben und auf die Variable "passwd" zugegriffen.
        msg: Dieses Playbook wurde von {{ passwd }} geschrieben.

# Das ist das zweite Play in diesem Playbook
- name: Installiere einen zweiten Server
  # Installiere auf allen Hosts im Inventory-File
  hosts: all
  # Hier beginnen Tasks für das zweite Play
  tasks:
    # Dies ist der erste Task vom zweiten Play
    - name: Installiere NGINX
      # Dies ist das Module YUM.
      yum:
        # Dies ist der Package-Name inkl. Version
        name: nginx.x86_64
        # Als Status können die folgenden Werte verwendet werden
        # 'present' or 'installed', 'latest', or 'absent' or 'removed'
        state: installed
  
  
